import "package:get/get.dart";

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "uz": {
          "select_languages": "Tilni tanlang",
          "input_phone_number": "Telefon raqamingizni kiriting",
          "phone_number": "Telefon raqam",
          "next": "Keyingisi",
          "continue_oferta_1": "Davom etish orqali siz ",
          "continue_oferta_2": "Ommaviy oferta ",
          "continue_oferta_3": "shartlariga roziligizni bildirasiz!",
          "input_sns_code": " telefon raqamiga yuborilgan sms kodni kiriting",
          "halal_meat_meal": "HALOL GO'SHT VA OZIQ OVQAT",
          "new": "Yangi",
          "wholesale": "Ulgurji",
          "to_cart": "Savatga",
          "please_registration_before": "Iltimos oldin ro'yhatdan o'ting!",
          "you_can_registration_with_your_phone":
              "Telefon raqami oqali ro'yhatdan o'tishingiz mumkin.",
          "registration": "Ro'yhatdan o'tish",
          "later": "Keyinroq",
          "main": "Asosiy",
          "search": "Qidiruv",
          "favorites": "Sevimlilar",
          "profile": "Profil",
          "search_from_store_": "Do'kondan qidirish...",
          "you_dont_have_favorites": "Sizda sevimli maxsulotlar mavjud emas!",
          "add_product": "Maxsulot qo'shish",
          "name_not_input": "Ism kiritilmagan",
          "editing": "O'zgartirish",
          "orders_history": "Buyurtmalar tarixi",
          "change_language": "Tilni o'zgartirish",
          "help": "Yordam",
          "delete_account": "Akkauntni o'chirish",
          "through_your_all_orders_delete":
              "Bu orqali sizning barcha buyurtmalaringiz o'chiriladi",
          "dismiss": "Berkitish",
          "delete": "O'chirish",
          "logout": "Tizimdan chiqish",
          "through_you_must_resign":
              "Bu orqali siz qayta tizimga kirishingizga to'g'ri keladi.",
          "editing_profile": "Profilni taxrirlash",
          "fullname": "Ism-Sharif",
          "save": "Saqlash",
          "delivery_information": "Yetkazib berish ma'lumotlar",
          "also_what_buy": "Yana nimadir sotib olasizmi?",
          "cart": "Savat",
          "delete_cart": "Savatni o'chirish",
          "do_you_delete_all_cart":
              "Savatdagi barcha mahsulotlarni o'chirmoqchimisiz?",
          "yes": "Ha",
          "no": "Yo'q",
          "cart_products": "Savatdagi mahsulotar",
          "cart_empty": "Savat bo'sh",
          "did_miss_any_product": "Aniq hech narsa esdan chiqmadimi?",
          "make_order": "Buyurtma berish",
          "deliver_information": "Yetkazib berish ma'lumotlari",
          "delivery_address": "Yetkazib berish manzili",
          "building_and_room_number": "Bino va xona raqami",
          "receiver_name": "Qabul qiluvchi ismi",
          "receiver_phone_number":
              "Qabul qiluvchi telefon raqami(010 XXXX XXXX)",
          "save_address_for_next_orders":
              "Manzilni keyingi buyurtmalar uchun saqlab qo'yish",
          "payment_type": "To'lov turi",
          "bankomat_mobile_bank": "Bankomat, Mobile bank",
          "bank_card": "Bank karta",
          "soon": "Tez kunda",
          "payment_informations": "To'lov ma'lumotlari",
          "missed_calculation_payment_amount":
              "To'lov summasini hisoblashda muammo bo'ldi!",
          "recalculation": "Qayta hisoblash",
          "total_products_": "Umumiy maxsulotlar: ",
          "delivery_amount_": "Yetkazib berish: ",
          "payment_amount_": "To'lov summasi: ",
          "order": "Buyurtma",
          "through_make_order_you_":
              "\"Buyurtma berish\" tugmasini bosish orqali siz ",
          "order_terms_": "Ommaviy oferta ",
          "accept_order_terms": "shartlariga roziligizni bildirasiz!",
          "please_fill_all_fields": "Iltimos barcha maydonlarni to'ldiring!",
          "order_id__": "Buyurtma #%s",
          "payment_amount__": "To'lov summasi: ",
          "thanks_for_order":
              "Buyurtmangiz uchun rahmat!\nTez orada to'lov uchun hisob raqami telefon raqamingizga SMS holatida yuboriladi.",
          "if_order_sms_not_receiver":
              "Agar SMS yetib kelmasa ilovadan quyidagi ketma-ketlikni bajaring: Profile->Mening buyurtmalarim->To'lov qilish ",
          "go_to_main_screen": "Asosiy oynaga o'tish",
          "address_": "Manzil: ",
          "receiver_": "Qabul qiluvchi: ",
          "order_time_": "Buyurtma vaqti: ",
          "payment_type_": "To'lov turi: ",
          "delivery_amount__": "Yetkazib berish summasi: ",
          "product_amount+": "Maxsulot summasi: ",
          "dissmiss_": "BERKITISH",
          "show_products_": "MAXSULOTLARNI KO'RSATISH",
          "pay_": "To'lov qilish",
          "payment_amount": "To'lov summasi",
          "pay_and_save_receipt":
              "Quyidagi hisob raqamlaridan biriga to'lov o'tkazing va kvitansiyani saqlab qo'ying! To'lov o'tkazilgandan so'ng buyurtmangiz yetkazib beriladi.",
          "accounts_for_pay": "Tolov uchun hisob raqamlar",
          "copied_": "Nusxa olindi!",
          "comment_for_order": "Buyurtma uchun izoh",
        },
        "en": {
          "select_languages": "Select language",
          "input_phone_number": "Enter your phone number",
          "phone_number": "Phone number",
          "next": "Next",
          "continue_oferta_1": "By continuing, you agree to the ",
          "continue_oferta_2": "Public offer ",
          "continue_oferta_3": "terms!",
          "input_sns_code": "Enter the SMS code sent to your phone number",
          "halal_meat_meal": "HALAL MEAT AND FOOD",
          "new": "New",
          "wholesale": "Wholesale",
          "to_cart": "To cart",
          "please_registration_before": "Please register first!",
          "you_can_registration_with_your_phone":
              "You can register with your phone number.",
          "registration": "Registration",
          "later": "Later",
          "main": "Main",
          "search": "Search",
          "favorites": "Favorites",
          "profile": "Profile",
          "search_from_store_": "Search from store...",
          "you_dont_have_favorites": "You don't have favorite products!",
          "add_product": "Add product",
          "name_not_input": "Name not entered",
          "editing": "Editing",
          "orders_history": "Order history",
          "change_language": "Change language",
          "help": "Help",
          "delete_account": "Delete account",
          "through_your_all_orders_delete": "This will delete all your orders",
          "dismiss": "Dismiss",
          "delete": "Delete",
          "logout": "Logout",
          "through_you_must_resign": "You will need to log in again.",
          "editing_profile": "Edit profile",
          "fullname": "Full name",
          "save": "Save",
          "delivery_information": "Delivery information",
          "also_what_buy": "Would you like to buy anything else?",
          "cart": "Cart",
          "delete_cart": "Delete cart",
          "do_you_delete_all_cart":
              "Do you want to delete all products in the cart?",
          "yes": "Yes",
          "no": "No",
          "cart_products": "Cart products",
          "cart_empty": "Cart is empty",
          "did_miss_any_product": "Did you forget anything?",
          "make_order": "Make order",
          "deliver_information": "Delivery information",
          "delivery_address": "Delivery address",
          "building_and_room_number": "Building and room number",
          "receiver_name": "Receiver's name",
          "receiver_phone_number": "Receiver's phone number (010 XXXX XXXX)",
          "save_address_for_next_orders": "Save address for next orders",
          "payment_type": "Payment type",
          "bankomat_mobile_bank": "ATM, Mobile bank",
          "bank_card": "Bank card",
          "soon": "Coming soon",
          "payment_informations": "Payment information",
          "missed_calculation_payment_amount":
              "There was an error calculating the payment amount!",
          "recalculation": "Recalculation",
          "total_products_": "Total products: ",
          "delivery_amount_": "Delivery: ",
          "payment_amount_": "Payment amount: ",
          "order": "Order",
          "through_make_order_you_":
              "By clicking 'Make order' you agree to the ",
          "order_terms_": "Public offer ",
          "accept_order_terms": "terms!",
          "please_fill_all_fields": "Please fill in all fields!",
          "order_id__": "Order #%s",
          "payment_amount__": "Payment amount: ",
          "thanks_for_order":
              "Thank you for your order!\nThe payment invoice will be sent to your phone number via SMS soon.",
          "if_order_sms_not_receiver":
              "If you don't receive an SMS, follow these steps in the app: Profile -> My orders -> Make payment",
          "go_to_main_screen": "Go to main screen",
          "address_": "Address: ",
          "receiver_": "Receiver: ",
          "order_time_": "Order time: ",
          "payment_type_": "Payment type: ",
          "delivery_amount__": "Delivery amount: ",
          "product_amount+": "Product amount: ",
          "dissmiss_": "DISMISS",
          "show_products_": "SHOW PRODUCTS",
          "pay_": "Pay",
          "payment_amount": "Payment amount",
          "pay_and_save_receipt":
              "Transfer the payment to one of the accounts below and save the receipt! Your order will be delivered after payment is made.",
          "accounts_for_pay": "Accounts for payment",
          "copied_": "Copied!",
          "comment_for_order": "Comment for order"
        },
        "ru": {
          "select_languages": "Выберите язык",
          "input_phone_number": "Введите ваш номер телефона",
          "phone_number": "Номер телефона",
          "next": "Далее",
          "continue_oferta_1": "Продолжая, вы соглашаетесь с ",
          "continue_oferta_2": "Публичной офертой ",
          "continue_oferta_3": "условиями!",
          "input_sns_code":
              "Введите SMS код, отправленный на ваш номер телефона",
          "halal_meat_meal": "ХАЛЯЛЬНОЕ МЯСО И ПРОДУКТЫ",
          "new": "Новое",
          "wholesale": "Оптовая продажа",
          "to_cart": "В корзину",
          "please_registration_before":
              "Пожалуйста, зарегистрируйтесь сначала!",
          "you_can_registration_with_your_phone":
              "Вы можете зарегистрироваться с вашим номером телефона.",
          "registration": "Регистрация",
          "later": "Позже",
          "main": "Главная",
          "search": "Поиск",
          "favorites": "Избранное",
          "profile": "Профиль",
          "search_from_store_": "Искать в магазине...",
          "you_dont_have_favorites": "У вас нет избранных продуктов!",
          "add_product": "Добавить продукт",
          "name_not_input": "Имя не введено",
          "editing": "Редактирование",
          "orders_history": "История заказов",
          "change_language": "Сменить язык",
          "help": "Помощь",
          "delete_account": "Удалить аккаунт",
          "through_your_all_orders_delete": "Это удалит все ваши заказы",
          "dismiss": "Отмена",
          "delete": "Удалить",
          "logout": "Выйти",
          "through_you_must_resign": "Вам нужно будет войти снова.",
          "editing_profile": "Редактировать профиль",
          "fullname": "Полное имя",
          "save": "Сохранить",
          "delivery_information": "Информация о доставке",
          "also_what_buy": "Хотите что-то еще купить?",
          "cart": "Корзина",
          "delete_cart": "Удалить корзину",
          "do_you_delete_all_cart": "Вы хотите удалить все продукты в корзине?",
          "yes": "Да",
          "no": "Нет",
          "cart_products": "Продукты в корзине",
          "cart_empty": "Корзина пуста",
          "did_miss_any_product": "Вы ничего не забыли?",
          "make_order": "Сделать заказ",
          "deliver_information": "Информация о доставке",
          "delivery_address": "Адрес доставки",
          "building_and_room_number": "Номер здания и комнаты",
          "receiver_name": "Имя получателя",
          "receiver_phone_number": "Номер телефона получателя (010 XXXX XXXX)",
          "save_address_for_next_orders":
              "Сохранить адрес для следующих заказов",
          "payment_type": "Тип оплаты",
          "bankomat_mobile_bank": "Банкомат, Мобильный банк",
          "bank_card": "Банковская карта",
          "soon": "Скоро",
          "payment_informations": "Информация об оплате",
          "missed_calculation_payment_amount":
              "Ошибка при расчете суммы платежа!",
          "recalculation": "Пересчет",
          "total_products_": "Всего продуктов: ",
          "delivery_amount_": "Доставка: ",
          "payment_amount_": "Сумма платежа: ",
          "order": "Заказ",
          "through_make_order_you_":
              "Нажимая 'Сделать заказ', вы соглашаетесь с ",
          "order_terms_": "Публичной офертой ",
          "accept_order_terms": "условиями!",
          "please_fill_all_fields": "Пожалуйста, заполните все поля!",
          "order_id__": "Заказ №%s",
          "payment_amount__": "Сумма платежа: ",
          "thanks_for_order":
              "Спасибо за ваш заказ!\nСчет на оплату будет отправлен на ваш номер телефона по SMS в ближайшее время.",
          "if_order_sms_not_receiver":
              "Если вы не получили SMS, выполните следующие шаги в приложении: Профиль -> Мои заказы -> Оплатить",
          "go_to_main_screen": "Перейти на главный экран",
          "address_": "Адрес: ",
          "receiver_": "Получатель: ",
          "order_time_": "Время заказа: ",
          "payment_type_": "Тип оплаты: ",
          "delivery_amount__": "Сумма доставки: ",
          "product_amount+": "Сумма продуктов: ",
          "dissmiss_": "ЗАКРЫТЬ",
          "show_products_": "ПОКАЗАТЬ ПРОДУКТЫ",
          "pay_": "Оплатить",
          "payment_amount": "Сумма платежа",
          "pay_and_save_receipt":
              "Переведите платеж на один из нижеуказанных счетов и сохраните квитанцию! Ваш заказ будет доставлен после оплаты.",
          "accounts_for_pay": "Счета для оплаты",
          "copied_": "Скопировано!",
          "comment_for_order": "Комментарий к заказу"
        },
      };
}
